/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { InvitationsService } from "../invitations.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { InvitationsCreateInput } from "./InvitationsCreateInput";
import { Invitations } from "./Invitations";
import { InvitationsFindManyArgs } from "./InvitationsFindManyArgs";
import { InvitationsWhereUniqueInput } from "./InvitationsWhereUniqueInput";
import { InvitationsUpdateInput } from "./InvitationsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class InvitationsControllerBase {
  constructor(
    protected readonly service: InvitationsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Invitations })
  @nestAccessControl.UseRoles({
    resource: "Invitations",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createInvitations(
    @common.Body() data: InvitationsCreateInput
  ): Promise<Invitations> {
    return await this.service.createInvitations({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        invitationCode: true,
        invitedBy: true,
        invitedUser: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Invitations] })
  @ApiNestedQuery(InvitationsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Invitations",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async invitationsItems(
    @common.Req() request: Request
  ): Promise<Invitations[]> {
    const args = plainToClass(InvitationsFindManyArgs, request.query);
    return this.service.invitationsItems({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        invitationCode: true,
        invitedBy: true,
        invitedUser: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Invitations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Invitations",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async invitations(
    @common.Param() params: InvitationsWhereUniqueInput
  ): Promise<Invitations | null> {
    const result = await this.service.invitations({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        invitationCode: true,
        invitedBy: true,
        invitedUser: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Invitations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Invitations",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateInvitations(
    @common.Param() params: InvitationsWhereUniqueInput,
    @common.Body() data: InvitationsUpdateInput
  ): Promise<Invitations | null> {
    try {
      return await this.service.updateInvitations({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          invitationCode: true,
          invitedBy: true,
          invitedUser: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Invitations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Invitations",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteInvitations(
    @common.Param() params: InvitationsWhereUniqueInput
  ): Promise<Invitations | null> {
    try {
      return await this.service.deleteInvitations({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          invitationCode: true,
          invitedBy: true,
          invitedUser: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
